apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: crossplane
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/murillodigital/20210130-kubernetes-day-crossplane
